#-------------定义oralce代理服务--------------------
apiVersion: v1
kind: Service
metadata:
  name: oralce-svc
  labels:
    app: oralce
spec:
  type: NodePort
  ports:
  - port: 1521
    targetPort: 1521
    name: oracle1521
  - port: 8080
    targetPort: 8181
    name: oralce8080
  selector:
    app: oralce
---

#-------------定义oralce部署--------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oralce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oralce
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oralce
    spec:
      containers:
        - image: oracle11g:latest
          name: oralce
          imagePullPolicy: Never
          ports:
            - containerPort: 1521
              name: oralce1521
            - containerPort: 8080
              name: oralce8080
          volumeMounts:
            - name: oralce-data
              mountPath: /u01/app/oracle
      volumes:
      - name: oralce-data
        nfs:
          path: /nfs
          server: 192.168.100.11
