---
# tasks file for master
- name: create install dir
  file: path=/usr/local/ssl/k8s state=directory mode=755
- name: copy_ca_file
  copy: src=/usr/local/ssl/k8s/{{item}} dest=/usr/local/ssl/k8s mode=755
  with_items:
    - ca.pem
    - ca-key.pem 
    - server.pem
    - server-key.pem
    - kube-proxy.pem
    - kube-proxy-key.pem
    - token.csv

- name: create install dir
  file: path={{item}} state=directory mode=755
  with_items:
    - "{{path}}"
- name: copy_bin
  copy: src=/root/server/bin/{{item}} dest={{path[1]}} mode=755
  with_items:
    - "{{node}}"

- name: config node
  template: src={{item}} dest={{path[0]}}/{{item.split('.')[:-1]|join('.')}}
  with_items:
    - kubernetes.j2
    - kubelet.config.j2

- name: config kubeconfig
  template: src={{item}} dest=/usr/local/ssl/k8s/{{item.split('.')[:-1]|join('.')}}
  with_items:
    - bootstrap.kubeconfig.j2 
    - kube-proxy.kubeconfig.j2

- name: config service
  template: src={{item}} dest=/usr/lib/systemd/system/{{ item.split('.')[:-1]|join('.') }}
  with_items:
    - kubelet.service.j2 
    - kube-proxy.service.j2

- name: start master
  systemd: name={{ item }} state=restarted enabled=yes daemon_reload=yes
  with_items:
    - kubelet
    - kube-proxy

- name: approve node
  ignore_errors: yes
  shell: kubectl certificate approve $(kubectl get csr |awk 'NR!=1{print $1}')
