---
# tasks file for common
- name: 关闭firewalld
  service: name=firewalld state=stopped enabled=no

- name: 关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"
  
- name: 关闭swap
  lineinfile:
    dest: /etc/fstab
    regexp: ".*swap"
    line: ""

- name: 即时生效
  shell: setenforce 0 ; swapoff -a

- name: copy_docker-ce.repo
  copy: src=docker-ce.repo dest=/etc/yum.repos.d/
- name: install docker-ce
  yum: name=docker-ce state=installed
- name: start_docker
  service: name=docker state=started enabled=yes
