version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    volumes:
      - /data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=liyang
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=liyang
      - MYSQL_PASSWORD=liyang
